$axure.loadCurrentPage({
  "url":"修改.html",
  "generationDate":new Date(1510280855446.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"eb58ffc5607247aab3077b315343626b",
    "type":"Axure:Page",
    "name":"修改",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6ba90f076fff47c1bf87af3c452e6214",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":1784,
              "height":916}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54512b48e735448eb169038e69fbb7c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":1784,
                  "height":916}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6ba90f076fff47c1bf87af3c452e6214":{
      "scriptId":"u0"},
    "54512b48e735448eb169038e69fbb7c3":{
      "scriptId":"u1"}}});