$axure.loadCurrentPage({
  "url":"工作日历.html",
  "generationDate":new Date(1510280855876.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d6ef645a7f064f8389bfa2d25d0689aa",
    "type":"Axure:Page",
    "name":"工作日历",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"54aa7abae200409288362fb6313dd237",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c19d0fe3d24a23ad8fd43d2d7f84a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日历/u0.png"}},
{
          "id":"9efc76281f3147559259d0bca866a821",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":230},
            "size":{
              "width":100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/工作日历/u2_line.png"}},
{
          "id":"b1b6be0ebebe4919a90ca015875705fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":227},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c4c0ee41a86432dae55845b9b7cac9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":227},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5e81fa10b7e44f49f40abec6e4ab3a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":50},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36e6f3cc6df04bd493663dc80a12b8c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":50},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日历/u5.png"}},
{
          "id":"2a10fc84a5ee40dab91a6c86a81b2c05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":175},
            "size":{
              "width":80,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93371fd356604db190e36e58c51d0a38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":402,
                  "y":175},
                "size":{
                  "width":80,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1749f493ed947f5991b15dbd3ccc314",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":187},
            "size":{
              "width":230,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/工作日历/u9_line.png"}},
{
          "id":"0380e51fcef04356b06332de54bb29d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":308},
            "size":{
              "width":230,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a32108d88216490289fffc2f5363f56a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":950,
                  "y":308},
                "size":{
                  "width":230,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34851b7160e24b09a3e1b1e0ce1728fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":322},
            "size":{
              "width":130,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/工作日历/u12_line.png"}},
{
          "id":"a9a9a299478f4b29a9e51c991986e5a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":462},
            "size":{
              "width":80,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57c2053d07d14797bd03d2a66ae01688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":462},
                "size":{
                  "width":80,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43312da9e62449b2b5254cd0a05f3785",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":479},
            "size":{
              "width":110,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/工作日历/u15_line.png"}},
{
          "id":"c9f8e06ae799427c86e685103cd32c8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1220,
              "y":240},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"565f51e3074c4f67bbfb15a04e1afbd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1220,
                  "y":240},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日历/u16.png"}},
{
          "id":"b223bc0bfc8d4dfcae38a5404cef6da0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1580,
              "y":240},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2b8adbe45bb43ccb70c2278d7f18ddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1580,
                  "y":240},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日历/u18.png"}},
{
          "id":"e37a42e84e3645909cecf71b74aa43a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1280,
              "y":214},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f31f427e22844c39599cfd4c91d2b4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1280,
                  "y":214},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bf3cc68c541425d884d725efe30cc49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1570,
              "y":214},
            "size":{
              "width":361,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b7cbaa9a34e4ad085e2784c70c9a2a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1570,
                  "y":214},
                "size":{
                  "width":361,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "54aa7abae200409288362fb6313dd237":{
      "scriptId":"u0"},
    "85c19d0fe3d24a23ad8fd43d2d7f84a5":{
      "scriptId":"u1"},
    "9efc76281f3147559259d0bca866a821":{
      "scriptId":"u2"},
    "b1b6be0ebebe4919a90ca015875705fe":{
      "scriptId":"u3"},
    "8c4c0ee41a86432dae55845b9b7cac9b":{
      "scriptId":"u4"},
    "f5e81fa10b7e44f49f40abec6e4ab3a7":{
      "scriptId":"u5"},
    "36e6f3cc6df04bd493663dc80a12b8c2":{
      "scriptId":"u6"},
    "2a10fc84a5ee40dab91a6c86a81b2c05":{
      "scriptId":"u7"},
    "93371fd356604db190e36e58c51d0a38":{
      "scriptId":"u8"},
    "b1749f493ed947f5991b15dbd3ccc314":{
      "scriptId":"u9"},
    "0380e51fcef04356b06332de54bb29d1":{
      "scriptId":"u10"},
    "a32108d88216490289fffc2f5363f56a":{
      "scriptId":"u11"},
    "34851b7160e24b09a3e1b1e0ce1728fb":{
      "scriptId":"u12"},
    "a9a9a299478f4b29a9e51c991986e5a6":{
      "scriptId":"u13"},
    "57c2053d07d14797bd03d2a66ae01688":{
      "scriptId":"u14"},
    "43312da9e62449b2b5254cd0a05f3785":{
      "scriptId":"u15"},
    "c9f8e06ae799427c86e685103cd32c8f":{
      "scriptId":"u16"},
    "565f51e3074c4f67bbfb15a04e1afbd8":{
      "scriptId":"u17"},
    "b223bc0bfc8d4dfcae38a5404cef6da0":{
      "scriptId":"u18"},
    "e2b8adbe45bb43ccb70c2278d7f18ddb":{
      "scriptId":"u19"},
    "e37a42e84e3645909cecf71b74aa43a3":{
      "scriptId":"u20"},
    "1f31f427e22844c39599cfd4c91d2b4e":{
      "scriptId":"u21"},
    "4bf3cc68c541425d884d725efe30cc49":{
      "scriptId":"u22"},
    "3b7cbaa9a34e4ad085e2784c70c9a2a5":{
      "scriptId":"u23"}}});