$axure.loadCurrentPage({
  "url":"新增.html",
  "generationDate":new Date(1510280855462.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f77013550cd84351a28a0ea931fd7724",
    "type":"Axure:Page",
    "name":"新增",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"995970ad5cb64eaf9a622be97144ac25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":1793,
              "height":932}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07105c448be14410bcab87f17d0d2546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":1793,
                  "height":932}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "995970ad5cb64eaf9a622be97144ac25":{
      "scriptId":"u0"},
    "07105c448be14410bcab87f17d0d2546":{
      "scriptId":"u1"}}});