$axure.loadCurrentPage({
  "url":"新建日历提醒.html",
  "generationDate":new Date(1510280855961.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"03cd88f67d20403082a046c66d398ec9",
    "type":"Axure:Page",
    "name":"新建日历提醒",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2760cfc964154a5e8f62a9fae222226b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d72870cd1854ea6998a9c6c4c7f9251",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建日历提醒/u0.png"}},
{
          "id":"aeb0ea94c33547bcb69023f553167100",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":360},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"521546d14b3c4353b5e093439c9938bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":360},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建日历提醒/u2.png"}},
{
          "id":"5d25ccd11ce74390a4f432d170ba8ea8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":20},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09eea3657cbd438ea094e0ff7d1dfca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1080,
                  "y":20},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建日历提醒/u4.png"}},
{
          "id":"28f997fe06594bd1998203cf8738d748",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":640},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e692cf7116f4c1da5874712ddfa67f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1080,
                  "y":640},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建日历提醒/u6.png"}},
{
          "id":"9b46025f65e74ea8af8643f4ff8be990",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1010},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce7a8552a46f4b0daff840ff2394ebc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":1010},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建日历提醒/u8.png"}},
{
          "id":"d2af4a1ce54c4eb38072573b26a1d579",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":301.198272705078,
              "y":241.307189941406},
            "size":{
              "width":295,
              "height":10},
            "rotation":"55",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新建日历提醒/u10_line.png"}},
{
          "id":"49fbea9d8a9a4f9aa819506e80bbe87a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":758,
              "y":295},
            "size":{
              "width":384,
              "height":10},
            "rotation":"135",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新建日历提醒/u11_line.png"}},
{
          "id":"01b7a18d2a6249158544ea24f00484ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":650},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64c121695a554c378640e5fdacf027ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1080,
                  "y":650},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建日历提醒/u6.png"}},
{
          "id":"6f103097de434fb6b8f10f1ee6be06ae",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":775.641357421875,
              "y":589.715209960938},
            "size":{
              "width":384,
              "height":10},
            "rotation":"219",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新建日历提醒/u11_line.png"}},
{
          "id":"fd3b890068b54753a0b7a78859177451",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":766},
            "size":{
              "width":521,
              "height":10},
            "rotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新建日历提醒/u15_line.png"}},
{
          "id":"c92cc2e6b7be444c80059741a74ecf19",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":435.753784179688,
              "y":609.246215820313},
            "size":{
              "width":200,
              "height":10},
            "rotation":"315",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新建日历提醒/u16_line.png"}},
{
          "id":"5d710141aefd4959a061a0accf05fdd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":694},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fe2a907fc454c74adebd61e4d3aaf15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":694},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ac4fc3e4c7f4e92ae48f3b67f9e99c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":690},
            "size":{
              "width":250,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a91453835df4904917646ae2bb2a350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":690},
                "size":{
                  "width":250,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工作日历/u5.png"}},
{
          "id":"6865c1ef454f4e26a1a9774ab8f9bc9d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":812},
            "size":{
              "width":276,
              "height":10},
            "rotation":"315",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新建日历提醒/u21_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2760cfc964154a5e8f62a9fae222226b":{
      "scriptId":"u0"},
    "1d72870cd1854ea6998a9c6c4c7f9251":{
      "scriptId":"u1"},
    "aeb0ea94c33547bcb69023f553167100":{
      "scriptId":"u2"},
    "521546d14b3c4353b5e093439c9938bf":{
      "scriptId":"u3"},
    "5d25ccd11ce74390a4f432d170ba8ea8":{
      "scriptId":"u4"},
    "09eea3657cbd438ea094e0ff7d1dfca3":{
      "scriptId":"u5"},
    "28f997fe06594bd1998203cf8738d748":{
      "scriptId":"u6"},
    "9e692cf7116f4c1da5874712ddfa67f7":{
      "scriptId":"u7"},
    "9b46025f65e74ea8af8643f4ff8be990":{
      "scriptId":"u8"},
    "ce7a8552a46f4b0daff840ff2394ebc0":{
      "scriptId":"u9"},
    "d2af4a1ce54c4eb38072573b26a1d579":{
      "scriptId":"u10"},
    "49fbea9d8a9a4f9aa819506e80bbe87a":{
      "scriptId":"u11"},
    "01b7a18d2a6249158544ea24f00484ea":{
      "scriptId":"u12"},
    "64c121695a554c378640e5fdacf027ba":{
      "scriptId":"u13"},
    "6f103097de434fb6b8f10f1ee6be06ae":{
      "scriptId":"u14"},
    "fd3b890068b54753a0b7a78859177451":{
      "scriptId":"u15"},
    "c92cc2e6b7be444c80059741a74ecf19":{
      "scriptId":"u16"},
    "5d710141aefd4959a061a0accf05fdd9":{
      "scriptId":"u17"},
    "9fe2a907fc454c74adebd61e4d3aaf15":{
      "scriptId":"u18"},
    "0ac4fc3e4c7f4e92ae48f3b67f9e99c1":{
      "scriptId":"u19"},
    "7a91453835df4904917646ae2bb2a350":{
      "scriptId":"u20"},
    "6865c1ef454f4e26a1a9774ab8f9bc9d":{
      "scriptId":"u21"}}});