$axure.loadCurrentPage({
  "url":"设置.html",
  "generationDate":new Date(1510280856255.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"65b8314db66140729bd22621f2a3e87f",
    "type":"Axure:Page",
    "name":"设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"999b07757f7a43bf8d4fc924c08df6e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9874c4c42c24879b2bd5e1fb4bcfbde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u0.png"}},
{
          "id":"8cd280270e4549ac958511fcf93fcf43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":52,
              "y":53},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39b8e8aebc324da8893b0e4febc690be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":52,
                  "y":53},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19f527150e274dbd8cb4d5a84bb64201",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":192,
              "y":53},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"750418e810004babbb86133d6cf491c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":192,
                  "y":53},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fc916ae345e4bf19134d5fd40232c08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF33FF33},
            "location":{
              "x":344,
              "y":54},
            "size":{
              "width":18,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d10216b3d2ee4507b753c68dee0f6f37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33FF33},
                "location":{
                  "x":344,
                  "y":54},
                "size":{
                  "width":18,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u6.png"}},
{
          "id":"f34ecd9539c44acbbb868b223beef4b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":78,
              "y":151},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5400bfa4af3d467fb29a1535b073d7dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":78,
                  "y":151},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33eb61d45685478f81457b5790606ba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":77,
              "y":195},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47f7cb1f4a8a44788cf025b6594153cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":77,
                  "y":195},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5daed6d42e4457ca7c203f8f3dd3f24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":550},
            "size":{
              "width":263,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0a7683af46e43e3853fea6d7d262a93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":550},
                "size":{
                  "width":263,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u14.png"}},
{
          "id":"e82f67961dee402893d3ac7c1ad53484",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":79},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e38313a5500d42e58c499d653aded084",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":79},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u18.png"}},
{
          "id":"e6a270ac6d144b4bb649b4d6326a48b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":153},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b32b76aa7bd043c09035e69a2f4369a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":153},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5658e23cd1984da6aa0c56e654c25def",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":193.5},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6f6c16b557a4300959946e6c817c660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":193.5},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u18.png"}},
{
          "id":"09061ee6d81b407eb78f07f6b9a3d535",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":50},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10b3f3c835ee46f582931748cdd1b05e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":50},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u20.jpg"}},
{
          "id":"1dff75c5eb8d4fb98a2c345d19486cf2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":200},
            "size":{
              "width":100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/工作日历/u2_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "999b07757f7a43bf8d4fc924c08df6e4":{
      "scriptId":"u0"},
    "f9874c4c42c24879b2bd5e1fb4bcfbde":{
      "scriptId":"u1"},
    "8cd280270e4549ac958511fcf93fcf43":{
      "scriptId":"u2"},
    "39b8e8aebc324da8893b0e4febc690be":{
      "scriptId":"u3"},
    "19f527150e274dbd8cb4d5a84bb64201":{
      "scriptId":"u4"},
    "750418e810004babbb86133d6cf491c7":{
      "scriptId":"u5"},
    "3fc916ae345e4bf19134d5fd40232c08":{
      "scriptId":"u6"},
    "d10216b3d2ee4507b753c68dee0f6f37":{
      "scriptId":"u7"},
    "f34ecd9539c44acbbb868b223beef4b5":{
      "scriptId":"u8"},
    "5400bfa4af3d467fb29a1535b073d7dc":{
      "scriptId":"u9"},
    "33eb61d45685478f81457b5790606ba0":{
      "scriptId":"u10"},
    "47f7cb1f4a8a44788cf025b6594153cb":{
      "scriptId":"u11"},
    "d5daed6d42e4457ca7c203f8f3dd3f24":{
      "scriptId":"u12"},
    "b0a7683af46e43e3853fea6d7d262a93":{
      "scriptId":"u13"},
    "e82f67961dee402893d3ac7c1ad53484":{
      "scriptId":"u14"},
    "e38313a5500d42e58c499d653aded084":{
      "scriptId":"u15"},
    "e6a270ac6d144b4bb649b4d6326a48b6":{
      "scriptId":"u16"},
    "b32b76aa7bd043c09035e69a2f4369a8":{
      "scriptId":"u17"},
    "5658e23cd1984da6aa0c56e654c25def":{
      "scriptId":"u18"},
    "a6f6c16b557a4300959946e6c817c660":{
      "scriptId":"u19"},
    "09061ee6d81b407eb78f07f6b9a3d535":{
      "scriptId":"u20"},
    "10b3f3c835ee46f582931748cdd1b05e":{
      "scriptId":"u21"},
    "1dff75c5eb8d4fb98a2c345d19486cf2":{
      "scriptId":"u22"}}});