$axure.loadCurrentPage({
  "url":"查询_1.html",
  "generationDate":new Date(1510280855662.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a6f0f14147cb4dc5b368d2c59f8478ed",
    "type":"Axure:Page",
    "name":"查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec1b4401cffc4662b6996afcd6a44dd2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":1782,
              "height":926}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6446f3eb687d4ce7b73b06afd0aa10b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":1782,
                  "height":926}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查询_1/u0.png"}},
{
          "id":"55c00d826b304552b65a8cedb3cd4d82",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":949},
            "size":{
              "width":570,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"add97393a04347bc984ffde6ceae101c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":949},
                "size":{
                  "width":570,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查询_1/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ec1b4401cffc4662b6996afcd6a44dd2":{
      "scriptId":"u0"},
    "6446f3eb687d4ce7b73b06afd0aa10b1":{
      "scriptId":"u1"},
    "55c00d826b304552b65a8cedb3cd4d82":{
      "scriptId":"u2"},
    "add97393a04347bc984ffde6ceae101c":{
      "scriptId":"u3"}}});