$axure.loadCurrentPage({
  "url":"手机端投顾版本.html",
  "generationDate":new Date(1510280855793.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b50e838983aa46bd8290253a10ba38cf",
    "type":"Axure:Page",
    "name":"手机端投顾版本",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"144e4fca35874e4dae8cdfa1d96a0c21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":440,
              "y":50},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c779baf6b9684d74abf64b0783fef802",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":440,
                  "y":50},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u0.png"}},
{
          "id":"dfeeb9417aef4814adf2727e28c7416a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":442,
              "y":53},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f468128aa454f578a86a6cbf0de3427",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":442,
                  "y":53},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31896c7748d241b78479ae016cb3a25f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":582,
              "y":53},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2257764244534286baee00febfc7e9ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":582,
                  "y":53},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98f563b898b5449198ef60809eb0f20f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF33FF33},
            "location":{
              "x":734,
              "y":54},
            "size":{
              "width":18,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdcc2fc105914b55bc56a118ea04120b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33FF33},
                "location":{
                  "x":734,
                  "y":54},
                "size":{
                  "width":18,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u6.png"}},
{
          "id":"cc6a6e31c04d43b8b10fc104095e2d61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":468,
              "y":105},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de5cbb97947e4d28a47332c300afd021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":468,
                  "y":105},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4986799d42a4cd292af7e773e91deb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":467,
              "y":139},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d27998f8d054eeb81b683b77befe8f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":467,
                  "y":139},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bad24a72916a4401be98cddc58755874",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":467,
              "y":175},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc98df5d0845451b8f35c0893f35d746",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":467,
                  "y":175},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2851a4791e1c4ddb97275f58b84471d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":230},
            "size":{
              "width":263,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"556b00ba41bc4636a20bb554186387ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":230},
                "size":{
                  "width":263,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u14.png"}},
{
          "id":"c4a15437d71c4e379df8e1d645eb0423",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":320},
            "size":{
              "width":263,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b37a0325eabb4bb3be3063e5bee2410d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":320},
                "size":{
                  "width":263,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u14.png"}},
{
          "id":"d60cf6386d62416781bd7054ee617e6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":80},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b7c606331c4c89af4fda3136341d2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":80},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u18.png"}},
{
          "id":"4c5dca1b10c746ba905a7a0fdf2f8fb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":320,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abf1ff4d639244778289e0c74eff10bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":320,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u0.png"}},
{
          "id":"5b1ebaa6f23f40c486a8169ff3c2b6e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":52,
              "y":53},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20e9d0b251a34164bc4c30b41e236f6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":52,
                  "y":53},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efbae6ff6fcf420db5787e002e78dd40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":192,
              "y":53},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e0b3fc0b59457d915ef8133d1bef44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":192,
                  "y":53},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"114acd784ad94fbeb4e79c71af0f783e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF33FF33},
            "location":{
              "x":344,
              "y":54},
            "size":{
              "width":18,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7d6f45075bb45bf80ec33de70a6fbe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33FF33},
                "location":{
                  "x":344,
                  "y":54},
                "size":{
                  "width":18,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u6.png"}},
{
          "id":"5135dfa8a91642028aa45ff1ac04ce14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":78,
              "y":105},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcc853d45b604c0ebf75a60dcae82c22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":78,
                  "y":105},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22718374e57042f9a9270b1218998f62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":77,
              "y":139},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb867420bc344a2899fb8c7dc4e83f47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":77,
                  "y":139},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f84663d12bb446febb43b502468d9cf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":77,
              "y":175},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da08ce214ed14b2daeca855b26504a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":77,
                  "y":175},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aed9fe77ebaa4c5397953e32df5c8f69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":230},
            "size":{
              "width":263,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dc88efedbfa4cddb3e8ed49f1e5c22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":230},
                "size":{
                  "width":263,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u14.png"}},
{
          "id":"318d4d5296c7451bb14ec2a5063d18ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":320},
            "size":{
              "width":263,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87d419a2fda148a68ae67c02e3c070d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":320},
                "size":{
                  "width":263,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u14.png"}},
{
          "id":"c8d870c0f0d3435cbe2e2af3a6a3266f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":80},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac71fd6b3e514d8a8073caa5deb3347e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":80},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机端投顾版本/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "144e4fca35874e4dae8cdfa1d96a0c21":{
      "scriptId":"u0"},
    "c779baf6b9684d74abf64b0783fef802":{
      "scriptId":"u1"},
    "dfeeb9417aef4814adf2727e28c7416a":{
      "scriptId":"u2"},
    "1f468128aa454f578a86a6cbf0de3427":{
      "scriptId":"u3"},
    "31896c7748d241b78479ae016cb3a25f":{
      "scriptId":"u4"},
    "2257764244534286baee00febfc7e9ff":{
      "scriptId":"u5"},
    "98f563b898b5449198ef60809eb0f20f":{
      "scriptId":"u6"},
    "fdcc2fc105914b55bc56a118ea04120b":{
      "scriptId":"u7"},
    "cc6a6e31c04d43b8b10fc104095e2d61":{
      "scriptId":"u8"},
    "de5cbb97947e4d28a47332c300afd021":{
      "scriptId":"u9"},
    "e4986799d42a4cd292af7e773e91deb6":{
      "scriptId":"u10"},
    "5d27998f8d054eeb81b683b77befe8f1":{
      "scriptId":"u11"},
    "bad24a72916a4401be98cddc58755874":{
      "scriptId":"u12"},
    "bc98df5d0845451b8f35c0893f35d746":{
      "scriptId":"u13"},
    "2851a4791e1c4ddb97275f58b84471d6":{
      "scriptId":"u14"},
    "556b00ba41bc4636a20bb554186387ee":{
      "scriptId":"u15"},
    "c4a15437d71c4e379df8e1d645eb0423":{
      "scriptId":"u16"},
    "b37a0325eabb4bb3be3063e5bee2410d":{
      "scriptId":"u17"},
    "d60cf6386d62416781bd7054ee617e6a":{
      "scriptId":"u18"},
    "28b7c606331c4c89af4fda3136341d2a":{
      "scriptId":"u19"},
    "4c5dca1b10c746ba905a7a0fdf2f8fb0":{
      "scriptId":"u20"},
    "abf1ff4d639244778289e0c74eff10bd":{
      "scriptId":"u21"},
    "5b1ebaa6f23f40c486a8169ff3c2b6e3":{
      "scriptId":"u22"},
    "20e9d0b251a34164bc4c30b41e236f6b":{
      "scriptId":"u23"},
    "efbae6ff6fcf420db5787e002e78dd40":{
      "scriptId":"u24"},
    "e0e0b3fc0b59457d915ef8133d1bef44":{
      "scriptId":"u25"},
    "114acd784ad94fbeb4e79c71af0f783e":{
      "scriptId":"u26"},
    "d7d6f45075bb45bf80ec33de70a6fbe8":{
      "scriptId":"u27"},
    "5135dfa8a91642028aa45ff1ac04ce14":{
      "scriptId":"u28"},
    "bcc853d45b604c0ebf75a60dcae82c22":{
      "scriptId":"u29"},
    "22718374e57042f9a9270b1218998f62":{
      "scriptId":"u30"},
    "cb867420bc344a2899fb8c7dc4e83f47":{
      "scriptId":"u31"},
    "f84663d12bb446febb43b502468d9cf2":{
      "scriptId":"u32"},
    "da08ce214ed14b2daeca855b26504a4f":{
      "scriptId":"u33"},
    "aed9fe77ebaa4c5397953e32df5c8f69":{
      "scriptId":"u34"},
    "8dc88efedbfa4cddb3e8ed49f1e5c22b":{
      "scriptId":"u35"},
    "318d4d5296c7451bb14ec2a5063d18ff":{
      "scriptId":"u36"},
    "87d419a2fda148a68ae67c02e3c070d4":{
      "scriptId":"u37"},
    "c8d870c0f0d3435cbe2e2af3a6a3266f":{
      "scriptId":"u38"},
    "ac71fd6b3e514d8a8073caa5deb3347e":{
      "scriptId":"u39"}}});